### ISSUE TITLE
mTLS using short lived certificates

### ISSUE THREAD

**Issue by devon-mar** [minio/kes#184]
#### What is the problem you want to solve?

I would like to use short lived certificates for mTLS. This can help address problems such as key compromise or revocation.

The documentation recommends using CA signed certificates but doesn't address problems such as certificate renewal.

#### How do you want to solve it?
Since certificates are short lived, the sha256 hash is therefore short lived. Instead of using the sha256 hash as an identity, use the certificate CN and/or SAN(s).

It looks like the server certificate is reloaded every 5 minutes. Other TLS certificates such as the Vault keystore client certificate will need to be reloaded periodically.

#### Additional context

1. Are there alternative solutions?
   Use a long lived certificate.

2. Would your solution cause a major breaking API change?
   Yes. The way identities are "identified" would need to be changed from sha256 hashes.
3. Anything else that is important?

**Comment by aead** [comment]
> I would like to use short lived certificates for mTLS. This can help address problems such as key compromise or revocation.

This is recommended and absolutely possible. 

> The documentation recommends using CA signed certificates but doesn't address problems such as certificate renewal.
> Since certificates are short lived, the sha256 hash is therefore short lived. Instead of using the sha256 hash as an identity, use the certificate CN and/or SAN(s).

This conclusion is not correct. You can renew a TLS certificate without changing the KES identity.
A TLS certificate consists of a public key, identifying information (e.g. Subject, SANs, KeyUsage etc.) and a signature from an issuing certificate.

Let's assume you generate a private key `S` and the corresponding pubic key `P`. Now, you generate a certificate signing request for your CA of choice and obtain a certificate `C1`  that is valid for e.g. 1 day. Once 24 have elapsed, `C1` becomes invalid. However, you can simply generate a new certificate signing request using the same  key pair `S` and `P` and obtain `C2`. In this case, `C1` and `C2` are perfectly valid certificates issued from a CA for the same public key.

However, since `P` hasn't changed, the identity used by KES hasn't changed as well.

**Comment by aead** [comment]
Closing this as answered.

**Comment by devon-mar** [comment]
> This conclusion is not correct. You can renew a TLS certificate without changing the KES identity.

I though that the identity was the certificate thumbprint, not a hash of the certificate public key.

https://github.com/minio/kes/blob/479bf349b02d3ac41929dd0fef55ecd147a425cf/cmd/kes/tool.go#L335

Thanks for the clarification!
