### ISSUE TITLE
output of "kes tool identity of" should be a JSON object 

### ISSUE THREAD

**Issue by gugalnikov** [minio/kes#34]
#### What is the problem you want to solve?

Most probably you want to automate the steps needed to configure KES server rather than copy/pasting from a terminal, and the current output is not very conducive to this (harder to parse); a standard way to return this kind of values is by using a simple JSON object (for example, that's how hashicorp Vault does it)

#### How do you want to solve it?
Return it as JSON or add a --json flag

#### Additional context

1. Are there alternative solutions?
add a --json flag 

2. Would your solution cause a major breaking API change?

NO
3. Anything else that is important?
NO

**Comment by aead** [comment]
Currently the KES CLI prints the identity (as human-readable / more expressive output):
```
kes tool identity of kes/root.cert

  Identity:  dd46485bedc9ad2909d2e8f9017216eec4413bc5c64b236d992f7ec19c843c5f
```
only when STDOUT is a terminal.

When you redirect STDOUT or writing to a shell variable you will receive only the raw identity. For example:
```
kes tool identity of kes/root.cert | cat
dd46485bedc9ad2909d2e8f9017216eec4413bc5c64b236d992f7ec19c843c5f
```

AFAIK this should be sufficient to parse the identity with tools / deploy scrips - since they can use literally the output produced by `kes tool identity of`.
Does this work for your scenario @gugalnikov ?

**Comment by gugalnikov** [comment]
ok, thanks for the quick answer, raw output works fine as well :)
