### ISSUE TITLE
Defaults for '--key' and '--cert' in 'kes identity new' are not working

### ISSUE THREAD

**Issue by rluetzner** [minio/kes#346]
#### Bug describtion

According to the documentation and the usage, I should be able to run the following command:

```bash
kes identity new --ip "192.168.0.182" --ip "10.0.0.92" Client-1
```

However, it fails with the following error message:

```text
Error: '--ip' requires a private key and certificate file. Set the '--cert' and '--key' flag
```

As far as I can see, this behavior started with Release 2023-02-15T14-54-37Z. I'm surprised nobody else noticed it before.

#### Expected behavior

The command should work and generate a public.key and private.crt file in the current directory -- as it did before. The usage shown with `kes identity new --help` even says that the parameters should default to these values.

#### Additional context

1. What version of Go are you using (`go version`)? Doesn't matter. I'm using a compiled binary.

2. What operating system and processor architecture are you using (`go env`)? Still doesn't matter.

3. Anything else that is important? Nope.

**Comment by rluetzner** [comment]
Sorry for the premature and mostly empty bug report. I accidentally hit 'Enter', before it was ready... 😩

**Comment by aead** [comment]
@rluetzner Thanks for the bug report. This behavior has been introduced by the API key support. Ref: https://github.com/minio/kes/releases/tag/2023-02-15T14-54-37Z

Going forward, we recommend using API keys to authenticate to KES. Hence, the `kes identity new` command now defaults to generating a copy-paste  API key instead of a private key / certificate file.

I will update the documentation to include the `--key` and `--cert` flags and also update the help text.

**Comment by rluetzner** [comment]
But KES still generates and uses the files, right? I still don't quite understand why the defaults shouldn't work anymore.

**Comment by aead** [comment]
By default KES does not generate these files anymore. Only when you explicitly want to generate a private key / certificate file we generate a certificate that gets written to disk. By default we just generate a single secret value that can easily be copy-pasted.

**Comment by rluetzner** [comment]
I'm still confused. So when I want to generate a new identity for specific IPs, I also want to generate these files in addition to the API key?

Because in the latest version the `--key` and `--cert` options are mandatory (when `--ip` is used at least once), so the files will definitely be created. Which to me sounds like the files are mandatory as well.

Can I just generate an API key and it will be valid for any origin IP?

----

Sorry, I know that I can answer these questions myself. I'll just need the time to look into it. 🙂 Feel free to ignore me and close this.

**Comment by aead** [comment]
@rluetzner KES authentication model does not rely on SANs (IPs DNS names, emails etc.)

There is a fundamental difference between the certificate a server requires and the certificate a KES client can use.
A TLS server requires a certificate that is valid for its IPs and/or DNS names. Otherwise, TLS clients will reject the certificate. In this case, the certificate maps from the IP or DNS name to a crypto. public key.

This is not the case for KES clients. A KES server only cares about the client identity which is a hash of the public key,
similar to SSH. Here, the certificate is just an encoding format to send the public key to the KES server during the TLS handshake.

An API key is simply the TLS private key. The public key and certificate can be computed on the fly. Hence, you end up with a secret ergonomics like an S3 secret key or API token. You can copy-paste it, pass it easily in config files etc.
An API key can be converted into a TLS private key / certificate and vice versa. What you loose is the X.509 metadata information, like for which IP the certificate is valid for or the signature of the issuing CA.

So, the difference between generating an API key and a client private key / certificate is the step where you encode the
public key as X.509 certificate and write the private key / certificate to disk. But for copy-pastable API keys you don't want / need these files anyway. 

***

So, the `--ip`, `--dns` and `--key` resp. `--cert` flags should be used when you want to generate a server certificate.
We do this in our guides for simplicity. You can use any other X.509 tooling  - like openssl - to generate your certificates.
Similarly, you can also use any other X.509 tooling to generate your API keys / resp. private key and certificate files for
your KES clients. However, since KES will mostly care about the identity anyway we provide a easy CLI command for this task.
